config/routes.rb
Rails.application.routes.draw do

  root to: 'session#home'

  resources :users

  resources :sessions

  get '/import', to: "session#import"

  post '/import', to: 'users#import'

  get '/login', to: 'session#login'

  post '/login', to: 'session#authenticate'

  get '/logout', to: 'session#logout'

  get '/auth/:provider/callback', to: 'session#connect'

  get '/playlists/partial', to: 'playlists#partial'

  post '/playlists/temp', to: 'playlists#temp'

  resources :playlists, only: [:index, :show, :create]

  get '/playlists/:id/partial', to: 'playlists#tracks'

  get '/playlists/:id/carousel', to: 'playlists#carousel'

  get '/playlists/player/:id', to: 'playlists#player'

  get '/playlists/track/:id', to: 'playlists#track'

end

app/controllers/session_controller.rb
require 'rspotify'
class SessionController < ApplicationController

  def login
    @user = User.new
  end

  def import

  end

  def logout
    session.delete(:user_id)
    flash.delete(:errors)
    redirect_to '/'
  end

  def register
    redirect_to '/auth/spotify'
  end

  def connect
    @user = User.new
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
  end

  def authenticate
    if user = User.authenticate(login_params[:email], login_params[:password])
      session[:user_id] = user.id
      redirect_to "/playlists"
    else
      flash[:errors] = user.errors.full_messages
      redirect_to '/login'
    end
  end

  private
  def login_params
    params.require(:user).permit(:email, :password)
  end

end

app/views/session/connect.html.erb
<div class = 'container'>
    <div class="jumbotron">
    <h1>Register For Relational Tones</h1>
    <% if !@user.errors.empty? %>
      <%= render partial: 'partials/errors' %>
    <% end %>
    <%= form_for(@user) do |f| %>
      <%= f.hidden_field(:email, value: @spotify_user.email) %>
      <%= f.hidden_field(:obj_hash, value: @spotify_user.to_json) %>
      <%= f.password_field :password, placeholder: "Password" %>
      <%= f.password_field :password_confirmation, placeholder: "Re-Enter Password" %>
      <%= f.submit "Register" %>
    <% end %>
  </div>
</div>

app/views/session/home.html.erb
<div class= "container">
  <div class = "jumbotron">
    <%= link_to "Register", new_user_path, class: 'register' %>
    <%= link_to "Login", '/login', class: 'login' %>
  </div>
</div>

app/views/session/import.html.erb
<div class = 'container'>
    <div class="jumbotron">
    <h1>Please Click This Link To Import Your Spotify Playlists</h1>
    <p>When the importing is completed you will be given a link to continue to the site</p>
    <div class="import-container">
      <a class="import-link" href="/import">Import Your Playlists</p>
    </div>
  </div>
</div>

app/views/session/login.html.erb
<div class = 'container'>
  <div class="jumbotron">
    <h1 class="">Login</h1>
    <% if flash[:errors] %>
      <%= render partial: 'partials/errors' %>
    <% end %>
    <%= form_for(@user, url: url_for(action: 'login', controller: 'session')) do |f| %>
      <%= f.email_field :email, placeholder: "Your Spotify Email" %>
      <%= f.password_field :password, placeholder: "Your Relational Tones Password" %>
      <%= f.submit "Login" %>
    <% end %>
  </div>
</div>

app/views/session/register.html.erb
<div class="container">
  <div class="jumbotron centerContent">
      <%= link_to 'Log in with Spotify', '/login', class: 'loginButton' %>
  </div>
</div>